openapi : 3.0.0

info:
  title: Full Fledged E-Commerce API
  description : Larning E-Commerce App Backend
  version: 1.1.0
  contact:
    email: agarwalsarthak456@gmail.com
    url: "https://sarthakag.netlify.com"

servers:
  - url : "{protocol}://localhost:4000/api/{version}"
    description : This server is for localhost
    variables: 
      version: 
        enum:
          - v1
          - v2
        default: v1
      protocol: 
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:      
      type: apiKey
      in: cookie
      name: token
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer 
          

